name: Build and Release Plugin

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch Tags
        run: |
          git fetch --tags
          git tag

      - name: Get and Increment Version
        id: get_version
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "1.0.0")
          echo "Dernière version : $LAST_TAG"
          IFS='.' read -r MAJOR MINOR PATCH <<< "$LAST_TAG"
          PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          while git rev-parse "refs/tags/$NEW_VERSION" >/dev/null 2>&1; do
            PATCH=$((PATCH + 1))
            NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          done
          echo "Nouvelle version : $NEW_VERSION"
          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Update Version in ocade-blocks.php
        run: |
          echo "Avant modification :"
          cat ocade-blocks.php
          sed -i "s/\(Version:\s*\)[0-9.]*/\1$VERSION/" ocade-blocks.php
          echo "Après modification :"
          cat ocade-blocks.php

      - name: Create version.txt
        run: echo $VERSION > version.txt

      - name: Setup Node.js with npm cache
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Prepare release build folder
        run: |
          mkdir release-build
          rsync -a --exclude=".git" --exclude=".github" --exclude="README.md" --exclude="*.zip" ./ release-build/

      - name: Minify all JS and CSS (including style.css)
        run: |
          # Minify JS files
          find release-build -type f -name "*.js" -exec ./node_modules/.bin/terser "{}" -o "{}" \;

          # Minify all CSS files, including any named style.css
          find release-build -type f -name "*.css" -exec ./node_modules/.bin/cleancss -o "{}" "{}" \;

      - name: Create Plugin ZIP
        run: |
          cd release-build
          zip -r ../ocade-blocks.zip * .[^.]*

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ocade-blocks.php version.txt
          git commit -m "Update version to $VERSION" || echo "No changes to commit"
          git push origin master

      - name: Create Git Tag
        run: |
          git tag $VERSION
          git push origin $VERSION

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: "Release ${{ env.VERSION }}"
          body: "Nouvelle version : ${{ env.VERSION }}"
          draft: false
          prerelease: false
          files: |
            ocade-blocks.zip
            version.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
